export const Leaders = [
  {
    id: 1,
    leaderName: "Mr. C.D Fakir",
    position: "Honourable Chairman",
    image: "",
    message1:
      "At CDF Infra Con, we are not just building infrastructure; we are shaping the future of India.",
    message2:
      "Our commitment to excellence in engineering consultancy and services has positioned us as a leader in the industry. With a wealth of experience and a portfolio of successful projects, we continually push the boundaries of what is possible in the field of infrastructure.",
    message3:
      "Every day, we challenge ourselves to redefine standards, innovate, and deliver the best to our clients. Our journey is one of relentless pursuit of excellence, fuelled by passion and dedication.",
    message4:
      "As we move forward, I encourage each one of you to embrace this spirit of innovation and strive for greatness in every endeavor. Together, we will continue to set new benchmarks and create a legacy that will be remembered for generations.",
    message5:
      "Thank you for being a part of this incredible journey. Let's continue to build a brighter future for India.",
  },
  {
    id: 2,
    leaderName: "Mrs. Fawziya M. Karjatkar",
    position: "Chairman & Managing Director",
    image: "",
    message1: "Welcome to CDF Infra Con Pvt. Ltd.",
    message2:
      "At CDF Infra Con Pvt. Ltd., we are redefining India's infrastructure landscape through our premier engineering consultancy and services. With extensive experience and a portfolio of successful projects, we continually push the boundaries of innovation in the infrastructure sector.",
    message3:
      "Our dedicated team is committed to excellence, tirelessly working to set new industry standards and deliver top-tier solutions to our clients. Driven by a passion to shape the future of India's infrastructure, we strive to create lasting, impactful projects that stand the test of time.",
    message4:
      "Thank you for visiting our website. We look forward to partnering with you to craft enduring and transformative infrastructure solutions.",
    message5: null,
  },
  {
    id: 3,
    leaderName: "Mr. Amer C Fakir",
    position: "Managing Director",
    image: "",
    message1: "Welcome to CDF Infra Con Pvt. Ltd.",
    message2:
      "We are at the forefront of defining India's infrastructure landscape through our exceptional Engineering Consultancy and Services. With a wealth of experience and numerous successful projects to our name, we pride ourselves on continually challenging the boundaries of what is possible in the field of infrastructure.",
    message3:
      "Our dedicated team works tirelessly to innovate and set new standards, esuring that we deliver the highest quality solutions to our clients. We are committed to excellence and driven by a passion to shape the future of India's infrastructure.",
    message4:
      "Thank you for visiting our website. We look forward to partnering with you to create lasting and impactful infrastructure solutions.",
    message5: null,
  },
  {
    id: 4,
    leaderName: "Mr. Amman C Fakir",
    position: "Managing Director",
    image: "",
    message1: "Welcome to CDF Infra Con Pvt. Ltd.",
    message2:
      "At CDF Infra Con Pvt. Ltd., we are proud to be at the forefront of shaping India's infrastructure landscape through our exceptional engineering consultancy and services. With a proven track record and a wealth of experience, we continually push the boundaries of what’s possible in the field of infrastructure development.",
    message3:
      "Our dedicated team is driven by a relentless passion for innovation, working tirelessly to set new benchmarks in quality and excellence. We are committed to delivering cutting-edge solutions that not only meet but exceed our clients' expectations.",
    message4:
      "Thank you for visiting our website. We are excited about the opportunity to partner with you in creating enduring and impactful infrastructure solutions for the future of India.",
    message5: null,
  },
];

export const OurTeams = [
  {
    id: 1,
    leaderName: "Mr. Dilip Palve",
    position1: "Resident cum Highway Engineer",
    position2: "Former executive Engineer (PWD)",
    image: "",
    message1: "Welcome to CDF Infra Con Pvt. Ltd.",
    message2:
      "At CDF Infra Con, we stand at the forefront of shaping India's infrastructure landscape with our unparalleled Engineering Consultancy and Services. With extensive experience and a portfolio of successful projects, we are dedicated to pushing the boundaries of what’s possible in the world of infrastructure.",
    message3:
      "Our team is passionate about innovation, continually setting new benchmarks to ensure that we deliver the highest quality solutions to our clients. We are committed to excellence, driven by the vision of crafting the future of India’s infrastructure.",
    message4:
      "Thank you for visiting our website. We look forward to collaborating with you to create enduring and impactful infrastructure solutions.",
    message5: null,
  },
  {
    id: 2,
    leaderName: "Mr. L.S. Joshi",
    position1: "Team Leader cum Senior Highway Engineer",
    position2: "Former Superintending Engineer",
    image: "",
    message1: "Welcome to CDF Infra Con Pvt. Ltd.",
    message2:
      "At CDF Infra Con, we are proud to be at the forefront of shaping India's infrastructure landscape. Our journey, marked by a wealth of experience and numerous successful projects has established us as a leader in Engineering Consultancy and services. We are committed to excellence and innovation, constantly pushing the boundaries of what is possible in the field of infrastructure. Our dedicated team works tirelessly to set new standards and redefine the industry, ensuring that we remain a benchmark for quality and reliability.",
    message3:
      "Join us as we continue to build a brighter, more robust future for India.",
    message4: null,
    message5: null,
  },
  {
    id: 3,
    leaderName: "Mr. Vijay B. Bhale",
    position1: "Resident Engineer cum Highway Engineer",
    position2: "Former Chief Engineer (PWD)",
    image: "",
    message1: "Welcome to CDF Infra Con Pvt. Ltd.",
    message2: "At CDF Infra Con, we are redefining India's",
    message3:
      "infrastructure through our comprehensive engineering consultancy and services. With a wealth of experience and numerous successful projects, we continually push the",
    message4:
      "boundaries of innovation and excellence in the infrastructure sector. Visit our website to learn more about our projects and services.",
    message5: null,
  },
  // {
  //   id: 4,
  //   leaderName: "Mr. Shivshankar Telamani",
  //   position1: "Highway Maintenance cum Resident Engineer",
  //   position2: null,
  //   image: "",
  //   message1: "Welcome to CDF Infra Con Pvt. Ltd.",
  //   message2:
  //     "As the Resident cum Highway Engineer at  CDF Infra Con, I am proud to be part of a team that is at the forefront of shaping India's infrastructure. Our commitment to excellence in engineering consultancy and services ensures that each project we undertake meets the highest standards of quality and efficiency.",
  //   message3:
  //     "With our extensive experience and innovative approach, we are dedicated to delivering infrastructure solutions that not only meet the needs of today but also pave the way for a sustainable and prosperous future. I invite you to explore our website at www.cdfic.com to learn more about our projects, our team, and our vision for the future.",
  //   message4:
  //     "Thank you for your interest in CDF Infra Con Pvt Ltd. We look forward to collaborating with you.",
  //   message5: null,
  // },
  // {
  //   id: 5,
  //   leaderName: "Mr. Naushad Khan",
  //   position1: "Bridge Engineer",
  //   position2: null,
  //   image: "",
  //   message1: "Welcome to CDF Infra Con Pvt. Ltd.",
  //   message2:
  //     "As the Bridge Engineer at CDF Infra Con, I am proud to be part of a team that is at the forefront of shaping India's infrastructure. Our commitment to excellence in engineering consultancy and services ensures that each project we undertake meets the highest standards of quality and efficiency. With our extensive experience and innovative approach, we are dedicated to delivering infrastructure solutions that not only meet the needs of today but also pave the way for a sustainable and prosperous future. I invite you to explore our website at www.cdfic.com to learn more about our projects, our team, and our vision for the future.",
  //   message3:
  //     "Thank you for your interest in CDF Infra Con Pvt Ltd. We look forward to collaborating with you.",

  //   message4: null,
  //   message5: null,
  // },
  {
    id: 6,
    leaderName: "Mr. Dilip Shinde",
    position1: "Team Leader cum Highway Engineer",
    position2: null,
    image: "",
    message1: "Welcome to CDF Infra Con Pvt. Ltd.",
    message2:
      "At CDF Infra Con, we stand at the forefront of shaping India's infrastructure landscape with our unparalleled Engineering Consultancy and Services. With extensive experience and a portfolio of successful projects, we are dedicated to pushing the boundaries of what’s possible in the world of infrastructure.",
    message3:
      "Our team is passionate about innovation, continually setting new benchmarks to ensure that we deliver the highest quality solutions to our clients. We are committed to excellence, driven by the vision of crafting the future of India’s infrastructure.",
    message4:
      "Thank you for visiting our website. We look forward to collaborating with you to create enduring and impactful infrastructure solutions.",
    message5: null,
  },
];

const OurProjects = [
  {
    status: "Completed",
    name: "Package 9 (NH-53 Badnera Road-Nagzari Kharda Road section from Belora Kherda Karanja Mangrulpir SH 280 and SH 274 and Murtizapur to Kherda SH 282 excluding Badnera Nagzari) for up gradation to Two Lane paved shoulder/ Four Lane configuration in the state of Maharashtra",
    length: "16.55 KM",
    client: "EPC Contractor Pentacle Consultant (I) Pvt Ltd.",
    category: "DPR",
    image: "image1.jpg",
  },
  {
    status: "Completed",
    name: "Four laning of Fagne to Gujarat-Maharashtra Border section of NH 6 from Km 510 to Km 650.79 in Maharashtra under NHDP Phase IV.",
    length: "141.59 km.",
    client: "GHV (India) Pvt Ltd",
    category: "Design",
    image: "image2.jpg",
  },
  {
    status: "Completed",
    name: "Four Laning of Khed-Sinnar Section of NH-50 from Km 42+000 to Km 177+000 (Design Length - 137.946 Km) under NHDP Phase IV in the state of Maharashtra on DBFOT Basis",
    length: "137.94 km.",
    client: "IL&FS Transportation Network Limited",
    category: "Design",
    image: "image3.jpg",
  },
  {
    status: "Completed",
    name: "Four Laning of Amravati- Chikhli section of NH-6 [Package-1 from km 166.000 (Amravati) to km 220.000 (Near Kurankhed)] in the state of Maharashtra",
    length: "54 km.",
    client: "Skylark",
    category: "Design",
    image: "image4.jpg",
  },
  {
    status: "Completed",
    name: "Amravati- Chikhli section of NH-6 [Package-II from km 220.000 (Near Kurankhed) to km 270.000 (Near Shelad)] in the state of Maharashtra",
    length: "40 km.",
    client: "BCCPIL",
    category: "Design",
    image: "image5.jpg",
  },
  {
    status: "Completed",
    name: "Widening of existing road from Km 144.400 to Km 249.000 on the Pune Solapur Section of NH-9.",
    length: "105 km.",
    client: "IL&FS Transportation Network Limited",
    category: "Design",
    image: "image6.jpg",
  },
  {
    status: "Completed",
    name: "Development of existing roads where bypasses are provided, in towns/village (Ule, Suratgaon, Malumbra, TuIjapur, Shingoli & Yedshi) On NH-211 (New-NH-52) & Naldurg,Omarga on NH-09 ,(New NH-65) In the State of Maharashtra on EPC Mode",
    length: "5 km.",
    client: "M/s Anant Chaitanya Consultancy Services",
    category: "Design",
    image: "image7.jpg",
  },
  {
    status: "Completed",
    name: "Improvement to Paud Kolvan Lonavala Road, MDR 26, Km 16/400 to 41/300, Tal. Maval, Dist. Pune, and associated roads",
    length: "71.16 km.",
    client: "Roadway Solution India Infra Limited",
    category: "PMC",
    image: "image8.jpg",
  },
  {
    status: "Completed",
    name: "Improvements to Malharpeth- Umbraj- Masur- Mayani - Diganchi -Mahud Pandharpur Road S.H.143 (Km 55/000 to 153/420) in the state of Maharashtra under MRIP on Hybrid Annuity Mode",
    length: "46.08 km.",
    client: "Roadway Solution India Infra Limited",
    category: "PMC",
    image: "image9.jpg",
  },
  {
    status: "Completed",
    name: "Improvement of roads connecting the tourist destination in Pune District (Panshet, Lonavala, Rajmachi. Torna, Sinhgad, Purandar)",
    length: "51.18 km.",
    client: "Roadway Solution India Infra Limited",
    category: "PMC",
    image: "image10.jpg",
  },
  {
    status: "Completed",
    name: "Improvements to Roads in Industrial Sector in Pune District (Hinjewadi, Chakan, Talegaon, Ranjangaon, Jejuri)",
    length: "58.36 km.",
    client: "Roadway Solution India Infra Limited",
    category: "PMC",
    image: "image11.jpg",
  },
  {
    status: "Completed",
    name: "Improvements to Mahabaleshwar Satara Rahimatpur Pusesawali Vita Road, SH - 140 in the state of Maharashtra under MRIP on Hybrid Annuity Mode.",
    length: "71.78 km.",
    client: "Roadway Solution India Infra Limited",
    category: "PMC",
    image: "image12.jpg",
  },
  {
    status: "Completed",
    name: "Consultancy Services for Feasibility study and preparation of Detail Project Report (DPR) for improvement and up-gradation of newly declared National Highways in the State of Uttar Pradesh.",
    length: "60 km.",
    client: "NHAI",
    category: "DPR",
    image: "image13.jpg",
  },
  {
    status: "Completed",
    name: "Construction of Eight lane access-controlled Expressway from Km 103.400 to Km 128.000 of Vadodara Mumbai Expressway in the State of Gujarat, UT of DNH and Maharashtra on Hybrid Annuity Mode under Bharatmala Pariyojana.",
    length: "24.60 km.",
    client: "Roadway Solution India Infra Limited",
    category: "PMC",
    image: "image14.jpg",
  },
  {
    status: "Completed",
    name: "Construction of Eight lane access-controlled Expressway from km 128.000 to km 154.600 of Vadodara Mumbai Expressway in the state of Gujarat on Hybrid Annuity mode under Bharatmala Pariyojna.",
    length: "26.60 km.",
    client: "Roadway Solution India Infra Limited",
    category: "PMC",
    image: "image15.jpg",
  },
  {
    status: "Completed",
    name: "Construction of Eight lane access-controlled Expressway from Km 154.600 to Km 190.000 of Vadodara Mumbai Expressway in the State of Gujarat on Hybrid Annuity Mode under Bharatmala Pariyojana.",
    length: "35.400 km.",
    client: "Roadway Solution India Infra Limited",
    category: "PMC",
    image: "image16.jpg",
  },
  {
    status: "Completed",
    name: "Balance Work under Phase -II for 4 laning of Khed Sinner Section of NH-50 (New NH-60) Comprising of the Stretches of Kalamb Bypass, Bhatkalwadi, and Alephata bypass in the State of Maharashtra.",
    length: "8.634 km.",
    client: "NHAI",
    category: "Safety Consultant",
    image: "image17.jpg",
  },
  {
    status: "Completed",
    name: "Balance work of Khed Ghat Realignment and Narayangaon Bypass on Khed - Sinnar section of NH - 60 in the State of Maharashtra on EPC Mode.",
    length: "9.319 km.",
    client: "NHAI",
    category: "Safety Consultant",
    image: "image18.jpg",
  },
  {
    status: "Completed",
    name: "Four Laning of NH-52 (New-NH 15) from end of Biswanath Chariali by-pass to Gohpur in the state of Assam on EPC mode.",
    length: "57.50 km.",
    client: "NHIDCL",
    category: "Safety Consultant",
    image: "image19.jpg",
  },
  {
    status: "Completed",
    name: "4-lanning of Balwara to Dhangaon section of NH-347BG & 753L in the State of Madhya Pradesh under Bharatmala Pariyojana Phase-I.",
    length: "40.40 km.",
    client: "NHAI",
    category: "Safety Consultant",
    image: "image20.jpg",
  },
  {
    status: "Ongoing",
    name: "Consultancy Services for Authority’s Engineer for Supervision of construction of four laning of NH 965 G from Baramati to Indapur in the State of Maharashtra under Bharatmala Pariyojna on EPC mode.",
    length: "42.131 km.",
    client: "NHAI",
    category: "Safety Consultant",
    image: "image21.jpg",
  },
  {
    status: "Ongoing",
    name: "Consultancy Services for Authority’s Engineer for Supervision of construction of four laning of NH 965 G from Indapur to Tondale in the State of Maharashtra under Bharatmala Pariyojna on EPC mode.",
    length: "24.76 km.",
    client: "NHAI",
    category: "Safety Consultant",
    image: "image22.jpg",
  },
  {
    status: "Ongoing",
    name: "Consultancy Services for Authority’s Engineer for Supervision of construction of four laning of NH 965 G from Indapur to Tondale in the State of Maharashtra under Bharatmala Pariyojna on EPC mode.",
    length: "22.94 km.",
    client: "NHAI",
    category: "Safety Consultant",
    image: "image23.jpg",
  },
  {
    status: "Completed",
    name: "Rehabilitation and Upgradation to Intermediate Lane configuration of Shri Kyari - Gumma section of NH-707 in the State of Himachal Pradesh under Green National Highways Corridor project (GNHCP) with the loan assistance of World Bank on EPC mode.",
    length: "19.900 km.",
    client: "NHAI",
    category: "Safety Consultant",
    image: "image24.jpg",
  },
  {
    status: "Ongoing",
    name: "Independent Engineer services for Supervision of Construction of Eight lane access-controlled Expressway from Amne to Bhoj Section-SPUR of Vadodara Mumbai Expressway in the State of Maharashtra on Hybrid Annuity mode under Bharatmala Pariyojana.",
    length: "24.6 km.",
    client: "NHAI",
    category: "Authority Engineer/ Independent Engineer",
    image: "image25.jpg",
  },
  {
    status: "Ongoing",
    name: "Four Lanning of existing 2/4 lane stretch from Lonand to Dive Ghat of Mohol – Alandi section of NH – 965 in the state of Maharashtra to be executed on EPC Mode under Bharatmala Pariyojana.",
    length: "54.500 km.",
    client: "NHAI",
    category: "Safety Consultant",
    image: "image26.jpg",
  },
  {
    status: "Ongoing",
    name: "Consultancy Services of Road Safety Audit and black spot rectification on NHs with PWD in the state of Punjab.",
    length: "500 km.",
    client: "MoRTH",
    category: "Safety Consultant",
    image: "image27.jpg",
  },
  {
    status: "Ongoing",
    name: "Consultancy Services of Supervision Consultant during O&M phase from Malshej Ghat to Ane Ghat on NH-61 in the state of Maharashtra.",
    length: "167.700 km.",
    client: "NHAI",
    category: "Supervision Consultant Operation & Maintenance",
    image: "image28.jpg",
  },
  {
    status: "Ongoing",
    name: "Consultancy Services for Supervision Consultant for 4/6L of Khed to Sinnar of NH - 60 in the State of Maharashtra.",
    length: "131.900 km.",
    client: "NHAI",
    category: "Supervision Consultant Operation & Maintenance",
    image: "image29.jpg",
  },
  {
    status: "Completed",
    name: "Detailed Project Report of additional Service Road / Slip Road in the stretch of Pune-Solapur section NH-65 in the State of Maharashtra as Standalone project on EPC Mode.",
    length: "16.645 km.",
    client: "NHAI",
    category: "DPR",
    image: "image30.jpg",
  },
  {
    status: "Ongoing",
    name: "Road Safety Audit of construction of 2-lanning with paved shoulder from Karnataka/Goa Border on NH-4A in the state of Karnataka on EPC Mode.",
    length: "84.120 km.",
    client: "NHAI",
    category: "Safety Consultant",
    image: "image31.jpg",
  },
  {
    status: "Ongoing",
    name: "Widening to 2-lane with paved shoulder of Adilabad-Bela section of NH353B in the state of Telangana under annual plan 2021-22 on EPC mode under NH(O).",
    length: "32.970 km.",
    client: "PWD Telangana – NH Division",
    category: "Safety Consultant",
    image: "image32.jpg",
  },
  {
    status: "Ongoing",
    name: "Construction of balance works (VUP, service Road, Drain, Junction Devetopment, Bus-Bay and FOB) for four laning of Tutjapur-Ausa section of NH-361 under Bharatmata Pariyojna in the State of Maharashtra on EPC Mode.",
    length: "55.835 km.",
    client: "NHAI",
    category: "Safety Consultant",
    image: "image33.jpg",
  },
  {
    status: "Ongoing",
    name: "Project Management Unit (PMU) at MRRDA for roads to be taken up for construction/up-gradation with Full Depth Reclamation Technology in Maharashtra.",
    length: "250 km.",
    client: "PMGSY",
    category: "DPR",
    image: "image34.jpg",
  },
  {
    status: "Ongoing",
    name: "Authority Engineer of White topping (TWT) along with reconstruction of 20 nos. culverts for NH-61 in the State of Maharashtra.",
    length: "167.700 km.",
    client: "NHAI",
    category: "Authority Engineer/ Independent Engineer",
    image: "image35.jpg",
  },
  {
    status: "Ongoing",
    name: "Authority Engineer of design and construction of using Thin White topping (TWT) including routine maintenance & balance work of Khed – Sinnar section of NH-60 in the State of Maharashtra as Standalone project on EPC Mode.",
    length: "131.900 km.",
    client: "NHAI",
    category: "Authority Engineer/ Independent Engineer",
    image: "image36.jpg",
  },
];
